$ANSIBLE_VAULT;1.1;AES256
65393762663734326566333365383263333963373232613839386330353137373238366533333664
6261616139313637323162623562333063346534663663620a363464343063633734376133643933
30323763383161643930626136343063383161336562366666393265646464316463316537326430
3136336636343932360a333236383536653730616233643765393032396562346533316437623037
37353636303831633233376234343331353930303134393939366530306566643939376535306238
35326632353238373966343734326239643561623330366162303535336233653264666365663633
66303531383135343562383232666361313963643633333330303233366461356333393339666263
61313833323362386365356330633839643036633335376364636264366163323135663132616238
65376565313732326264333564656230383666383538373762356566396533636339396535373532
61343464653534343932306235623066336639313439653165386134303639633235643934366131
613662386136626538333862313063616230
