---
# Configure fail2ban defaults

fail2ban_ignoreip:
  - 127.0.0.1/8
  - 172.31.16.0/20 # AWS VPC range
  - "{{ admin_ip_address }}"

fail2ban_services:
  - name: sshd
  - name: apache-auth
    logpath: /var/log/apache2/*error.log
  - name: apache-overflows
    logpath: /var/log/apache2/*error.log
  - name: apache-badbots
    logpath: /var/log/apache2/*access.log
  - name: apache-noscript
    logpath: /var/log/apache2/*error.log
  - name: apache-nohome
    logpath: /var/log/apache2/*error.log
  - name: apache-botsearch
    logpath: /var/log/apache2/*error.log
  - name: apache-fakegooglebot
    logpath: /var/log/apache2/*access.log
  - name: apache-shellshock
    logpath: /var/log/apache2/*error.log
  - name: php-url-fopen
    logpath: /var/log/apache2/*access.log
