$ANSIBLE_VAULT;1.1;AES256
32396661643363656630633661343430656361653038313039393266383866616466633939623333
3930323138356237376438633866356365633336623230350a613330653031313337393263663031
34653237616564326339373131303262636231313830656530656236613938613264353532316364
3863666134353035620a653038626634623961386561613937396632623233363761316236303937
33623733366466636631316531366239633138303133306532336532616135616362663838646231
6234613234646166663831316634323532366138366335633031
